awslabs/amazon-kinesis-producer

java/amazon-kinesis-producer/src/main/java/com/amazonaws/kinesis/producer/Configuration.java
In some contexts, it is inconvenient to load from a properties file. This enables me to load a Configuration from various other sources.
=> extract Configuration.fromProperties

java/amazon-kinesis-producer/pom.xml
A small fix.
We had to exclude this particular dependency in our project, because it was randomly overriding our own configuration, resulting in missing log files of our service. I believe that as a library you should only include the SLF4J API. See http://www.slf4j.org/faq.html#configure_logging
=> make slf4j impl. optional dependency, so it doesn't break end user logging

bootstrap.sh
Curl by default will include the system CA bundle, and will pass that to
OpenSSL when configuring the connection.  Unfortunately when OpenSSL
get a CA File that it can't open, it never event attempts to use the CA
Directory parameter.
=> Don't Include System Default CA Bundle

aws/utils/backtrace/backtrace.h, aws/utils/backtrace/bsd_backtrace.cc, aws/utils/backtrace/gcc_backtrace.cc, aws/utils/backtrace/null_backtrace.cc, aws/utils/signal_handler.cc, aws/utils/signal_handler.h, java/amazon-kinesis-producer/pom.xml
Set signal handling to ignore SIGPIPE.  This will prevent a spurious error message.
=> Don't report SIGPIPE as an error

README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
* The native process will no longer report SIGPIPE signals as an error with a stack trace.
* Allow the use of SIGUSR1 to trigger a stack trace. This stack trace will only report for the thread that happened to receive the signal.
=> Release 0.12.2 of the Amazon Kinesis Producer

java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/FileAgeManager.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/FileAgeManagerTest.java
The Kinesis Producer Library extracts its files to a temporary
directory.  By default that is 'java.io.tmpdir', which maybe subject to
a cleanup policy.  If certain files are removed the kinesis_producer
process maybe unable to send data.
This change should keep the age of the files moving forward, and prevent
temporary cleanup scripts from removing important files.
=> Keep File Age Recent to Prevent Cleanup

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java
=> Wrap process.waitFor() in a try-finally that calls shutdown

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java
Fixes #91 
The approach of creating & locking the executable file in a non-atomic way can lead to a race condition. Instead, we should use a dedicated lockfile to coordinate access to the executable.
=> Use lockfile to coordinate access to binary executable

CMakeLists.txt, aws/kinesis/core/configuration.h, aws/kinesis/core/kinesis_producer.cc, aws/kinesis/protobuf/config.pb.cc, aws/kinesis/protobuf/config.pb.h, aws/kinesis/protobuf/config.proto, aws/mutex.h, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/protobuf/Config.java
This allows changing the threading model from a per request model to a pooled model.  
This uses a queue, and thread pool to execute requests to Kinesis.  This limits the number of threads that the native process may use.  Under extremely heavy load this can increase latency significantly more than the per request model.  
This is the current default for 0.12.x versions of the KPL, and creates a thread for each request to Kinesis.  Under heavy load this can create a very large number of threads, which may cause resource exhaustion.
Updated compiler for Linux from GCC 4.9 to GCC 6.3.
=> Add Thread Pooling as a Threading Policy

java/amazon-kinesis-producer/pom.xml
Removed the version range specifier for aws-java-sdk-core.
See PR #84
=> Remove the Version Range for Dependencies

CMakeLists.txt, aws/utils/wrap_memcpy.c, java/amazon-kinesis-producer/pom.xml
During the upgrade to a newer compiler the version of memcpy changed to a newer version of glibc.  This has caused some problems with older versions of Linux.
This change prevents the newer version of memcpy from being linked in to allow using the KPL on older Linux variants.
=> Force an older version of glibc by preventing the use of 2.14 memcpy.

bootstrap.sh
Remove some unneeded link, and include flags.
When using new compiler make sure to set LD_LIBRARY_PATH to the location of the libraries for the compiler.
Disabled customer engines for OpenSSL which was causing issues generating static archives, and causing curl to not include TLS/SSL support.
Added a CMake define required when building AWS C++ SDK on macOS Sierra (10.12.5).
=> Update the Bootstrap Script For Newer Compiler

README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
* Revert to an older version of glibc.
* [PR #108](https://github.com/awslabs/amazon-kinesis-producer/pull/108)
* Update bootstrap.sh to include new compiler options for the newer version of GCC.
* [PR #109](https://github.com/awslabs/amazon-kinesis-producer/pull/109)
=> Release 0.12.5 of the Amazon Kinesis Producer Library

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Attempt.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/IKinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/UserRecord.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/UserRecordResult.java
Introduced interface on KinesisProducer for testability/mockability.
Introduced UserRecord object and KinesisProducer.addUserRecord(UserRecord) method.
@pfifer 
This commit was done with 100% backwards compatibility in mind.
=> Make KPL consumers more testable

java/amazon-kinesis-producer-sample/default_config.properties, java/amazon-kinesis-producer/.gitignore, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfigurationTest.java
Fixes issue https://github.com/awslabs/amazon-kinesis-producer/issues/124
This is the quick fix imho. The long term fix for the property resolution is to migrate to the KCL approach I described in the issue. This would also then allow support for CredentialProviders too.
=> Fix issue #124 - threading properties

java/amazon-kinesis-producer-sample/default_config.properties
Issue related: https://github.com/awslabs/amazon-kinesis-producer/issues/119
=> fix default_config.properties

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java
This change updates calls to ExecutorService.submit (mostly deamons), to
call ExecutorService.execute instead.  The submit variant returns a
Future which will contain any errors that are thrown from the Runnable.
However, nothing was checking these throwables for errors.  If an error
happens, for example an OutOfMemoryError or RuntimeException thrown from
a custom AWSCredentialsProvider, the deamon thread will die without ever
logging any error information.  Changing this to use execute allows the
Thread's UncaughtExceptionHandler or the default
UncaughtExceptionHandler to properly handle the failure.  At a minimum
this allows the error to be logged.  Some clients may wish to respond to
an OutOfMemoryError by taking a more severe action, such as restarting
the service.  Given that failure …
=> Bubble Throwables when executing Runnables

README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
* Added Windows support
The 0.12.x version now supports Windows.
The Windows version is currently mastered on the branch `windows`, which will be merged at a later date.
The build instructions for Windows are currently out of date, and will be updated at a later date.__
* Issue #113
* Issue #74
* Issue #73
* Removed the libc wrapper
The libc wrapper lowered the required version of glibc.  The KPL is now built with an older version of libc, which removes the need for the wrapper.
* PR #139
* Set the minimum required version of macOS to 10.9.
The KPL is now built against macOS 10.9.
* Issue #117
* PR #138
* Allow exceptions to bubble to the thread exception handler for Daemon threads.
Exceptions that occur on daemon threads will now be allowed to propagate to the thread exception handler. …
=> Release 0.12.6 of the Amazon Kinesis Producer Library

CMakeLists.txt
Removed the libidn, as it's no longer required.
Use the correct formulation of find_library for the static version of libuuid.
=> Remove libidn From Linking, and Correctly Use Static UUID

bootstrap.sh
Disable clock_gettime support in curl for macOS to provide backwards compatibilty
with macOS 10.11 and earlier.
=> Disable clock_gettime for macOS

aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/CertificateExtractor.java
The certificates weren't properly being registered for file age
management if they already exists.  This now ensures that certificates
are registered correctly.
=> Advance Version, and Fix File Age Registration for Certificates

README.md, java/amazon-kinesis-producer/pom.xml
* Ensure that all certificates are registered the `FileAgeManager` to prevent file sweepers from removing them
* PR #165: https://github.com/awslabs/amazon-kinesis-producer/pull/165
* Upgrade aws-java-sdk-core to 1.11.245
* Issue #164: https://github.com/awslabs/amazon-kinesis-producer/issues/164
* PR #166: https://github.com/awslabs/amazon-kinesis-producer/pull/166
=> Release v0.12.8 of the Amazon Kinesis Producer Library

README.md
Added a notice covering the upcoming migration of Kinesis Data Streams
to new certificates issued by Amazon Trust Services.
=> Added notice about upcoming Kinesis Streams certificate changes

CMakeLists.txt, aws/auth/mutable_static_creds_provider.cc, aws/auth/mutable_static_creds_provider.h, aws/auth/test/mutable_static_creds_provider_test.cc
Removed the spin lock from the credentials class.  The spin lock was really expensive and problematic performance wise.  
The new approach uses an optimistic read via an interlocked change process to allow the get method to detect a change and retry the load of the credentials.
=> Remove spin lock from credentials

java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/HashedFileCopier.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/HashedFileCopierTest.java, java/amazon-kinesis-producer/src/test/java/log4j.properties, java/amazon-kinesis-producer/src/test/resources/logback.xml, java/amazon-kinesis-producer/src/test/resources/test-data/test.txt
Use message digest filter streams to limit the required memory during
native executable extraction.
=> Extract the native component without copying it into memory

java/amazon-kinesis-producer/pom.xml
Removing log4j from effectively removed an expected class that is
available in newer versions of SLF4J.  This issue only affected unit
tests, and upgrading to the newer version fixes the unit tests.
=> Update the SLF4J dependency version

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java
Runtime exceptions while updating credentials will no longer kill the
credential update thread.
Interrupted exceptions can be thrown while a thread pool/executor is
being shutdown.  This now handles that case without a message.
Fixes #49 and Fixes #34
=> Handle exceptions while updating credentials better

CMakeLists.txt, aws/auth/mutable_static_creds_provider.cc, aws/auth/mutable_static_creds_provider.h, aws/auth/test/mutable_static_creds_provider_test.cc
Switched to use a shared_ptr for credential transfer, and thread_local for normal usage.  
This gets rid of a bug that could occur with the previous approach around destruction of the string objects, while preserving performance in most cases.
=> Use a shared_ptr and thread_local to store credentials for use

README.md, aws/kinesis/core/configuration.h, aws/metrics/metrics_manager.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.java
* Support for additional AWS regions.
* Bug fix to avoid Heap Out of Memory Exception.
* [PR #225](https://github.com/awslabs/amazon-kinesis-producer/pull/225)
* [Issue #224](https://github.com/awslabs/amazon-kinesis-producer/issues/224)
* Support for additional AWS regions.
* Update the CloudWatch upload logic to timeout retries at 10 Minutes instead of 30 Minutes and backoff between retries.
=> Prepare for release 0.12.10 of the Amazon Kinesis Producer Library

README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
* Bump up the version to 0.12.11. Maven release updated with working binaries.
* Fixes [Issue #231](https://github.com/awslabs/amazon-kinesis-producer/issues/231)
=> Prepare for release 0.12.11 of the Amazon Kinesis Producer Library

bootstrap.sh
#206
Update bootstrap.sh to remove cloudfront library locations with original locations since cloudfront location does not seem to exist anymore.
=> Updating bootstrap to work around cloudfront which doesn't exist

bootstrap.sh
*Add C++ compile flags to bootstrap.sh to compile aws-sdk-cpp with gcc 7*
The dependency aws-sdk-cpp was failing to build with gcc7.4 because of two warnings that are new to gcc7.0. These warnings were  for implicit-fallthrough and int-in-bool-context. This change sets the CXXFlags in bootstrap.sh to build the aws sdk cpp dependency.
=> Add C++ compile flags to bootstrap.sh to compile aws-sdk-cpp with gcc 7

java/amazon-kinesis-producer-sample/README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/SampleConsumer.java, java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/SampleProducer.java
Improve the Sample: 1. Fix dependency issues in pom.xml 2. In the producer stop using a threadpool to complete every future for every record sent 3. In the producer allow stream name region and run duration to be provided as optional positional parameters on the command line. 4.In the producer reduce aggregation period to allow records to be sent every 2 seconds to exercise the record sending code.  5. In the consumer allow stream name and region to be provided as command line parameters.
=> Improve the Sample: Make it possible to run the producer and consumer without editing it.

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.java
KinesisProducerConfiguration comment has a typo for the `getRecordMaxBufferedTime` and `setRecordMaxBufferedTime` method comments
=> Fix Typo in KinesisProducerConfiguration

CMakeLists.txt, aws/kinesis/main.cc, aws/utils/logging.cc, bootstrap.sh
Update the cpp AWS SDK used in the native kinesis producer: Some build changes since the AWS SDK build flow has changed. Change included header files to reflect renamed files. Implement a flush method in logging.cc since the underlying AWS SDK abstract class requires it.
Tested with sample and doing update shard count while the sample runs.
=> Update the cpp AWS SDK used in the native kinesis producer

aws/kinesis/core/kinesis_producer.cc
*Issue #, if available: 259
China Ningxia region (cn-northwest-1) was launched in Dec, 2017. The corresponding endpoint is not in current code. I added it by mocking the endpoint for Beijing region (cn-north-1). Due to lack of my test environment, I didn't test my code. Please help verify. Thank you.
=> Add endpoint for China Ningxia region

aws/kinesis/core/pipeline.h, aws/utils/time_sensitive.h
When aggregation is enabled and all the buffer time is consumed for aggregating User records into Kinesis records, allow some additional buffer time for aggregating Kinesis Records into PutRecords calls.
Before this fix, when aggregation is enabled and all the available buffer time is spent buffering user records into Kinesis records, PutRecords calls were made with very few records per batch (often just a single one). This effect was stronger when the record buffer time was low and the destination stream was larger (> 200 shards). This lead to higher load on the producers and potential instability while writing to larger streams.
This change provides some additional buffer time, only when aggregation is enabled, to allow more Kinesis records to be batched into …
=> Allow some additional buffer time for aggregating Kinesis Records into PutRecords calls

java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
*Issue*
https://github.com/advisories/GHSA-mvr2-9pj6-7w5j
https://github.com/advisories/GHSA-m8p2-495h-ccmh
upgrade org.hibernate.validator:hibernate-validator 6.0.2.Final -> 6.0.18.Final
upgrade com.google.guava:guava 18.0 -> 24.1.1-jre
=> Upgrade dependency flagged by Dependabot alerts

bootstrap.sh, java/amazon-kinesis-producer/pom.xml
- Upgrade Guava to 26.0-jre
- Update BOOST C++ Libraries link as cert expired on the older link
=> upgrade guava, boost C++ link

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.java
*Issue # https://sim.amazon.com/issues/Streamy-4141
*Description of changes:* This change allows user to override the ca cert path in KPL to a their own path hence allowing to provide custom paths for specific use cases.
=> Adding kpl config to allow ca cert path to be overriden.

aws/kinesis/core/retrier.cc
The Issue is that when a customer deletes a stream after scaling the stream for multiple times and then creates the stream with same number of shards. The KPL producer is going into continuous retry storm with error "Wrong Shard ErrorMessages: [Record did not end up in expected shard ... "  but no "Record went to shard x instead of shard y.." log message. 
This means, KPL has never tried to update the shard map, which is done at line 208 in retrier.cc file.
This is a bug where KPL assumes that a record can go into a different shard only when the same stream has scaled and then updates the shard Map. Hence removing this check ("The actual destination shard is newer than the predicted shard.")
Hence removing the extra check "The actual …
=> KPL goes into a continous retry storm if the stream is deleted and re-created

java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/SampleProducer.java, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/IKinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/UnexpectedMessageException.java
*Description of changes:* Adding metrics for future time.
Old PR Link : https://github.com/awslabs/amazon-kinesis-producer/pull/319
=> Adding kpl metric to track the time for oldest future in processing

.travis.yml, CMakeLists.txt, bootstrap.sh, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java
*Issue #, if available:* #258
Add support for building and using binaries for multiple architectures, specifically arm64 to support AWS Graviton based instances, but this should also enable Apple M1 based OS X systems as well. Bumped Boost slightly to a version that includes Arm support and added the architecture to the path for kinesis_producer.
=> Add support for building multiple architectures, specifically arm64

aws/kinesis/core/retrier.cc
*Description of changes:* Fixing KPL not emmiting Kinesis PutRecords call context metrics.
=> Fixing KPL not emmiting Kinesis PutRecords call context metrics.

java/amazon-kinesis-producer/pom.xml
**Description of changes:**
Support the JSON data format with Glue Schema Registry. Version 1.1.0 of `schema-registry-serde` introduces JSON data format support.
**Testing**
Changes can be built successfully and JSON data format is tested with Kinesis Sample Producer. Verified that there are no regressions with Avro.
=> Support Glue Schema Registry JSON data format

java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java-templates/KinesisProducerLibraryPackage.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
Sets "kpl" as UserAgentApp config in configuration. This allows the Glue Schema Registry library to emit metrics.
*Testing*
Build successful.
Sample UserAgent emitted,
```
autoreg/0:compress/0:secdeser/0:app/kpl-0.14.9/1.1.3
```
=> Emit usage metrics for glue schema registry

java/amazon-kinesis-producer/pom.xml
Upgrading version of logback classic for [CVE-2017-5929](https://nvd.nist.gov/vuln/detail/CVE-2017-5929). 
=> Upgrading logback-classic from 1.2.0 to 1.2.6

.travis.yml, bootstrap.sh
CI has been failing since curl breaks if the system's CA cert is stale. Adding a step in the build scripts to pull the latest CA cert and use that for the curl requests that the build script uses.
Before:
```
curl: (60) The certificate issuer's certificate has expired.  Check your system date and time.
More details here: http://curl.haxx.se/docs/sslcerts.html
```
Currently this passes, tested this by running the build script on a AL2012 host and verifying the bootstrap script is able to pull dependencies via curl.
=> Fixing build issues due to stale CA certs

bootstrap.sh
The curl native binary that is being shipped with latest amazon-kinesis-producer Java library is getting flagged with security vulnerability in our scans.
The version of curl getting shipped in latest library is 7.77.0 which has vulnerabilities : https://curl.se/docs/vuln-7.77.0.html
The latest version of curl binary is 7.81.0..
=> Update curl version from 7.77 to 7.81

.travis.yml, bootstrap.sh
=> Fix cpp branch

.gitignore, aws/kinesis/main.cc, bootstrap.sh, java/amazon-kinesis-producer-sample/.gitignore, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/CertificateExtractorTest.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/KinesisProducerTest.java, java/amazon-kinesis-producer/src/test/resources/logback-test.xml
1. Enhanced `bootstrap.sh` to make upgrades simpler.
1. Upgraded following libraries used in `bootstrap`
* boost: 1.76.0 -> 1.80.0
* zlib: 1.2.11 -> 1.2.12
* curl: 7.81.0 -> 7.85.0
* openSSL: 1.0.2u -> 1.1.1q
* protobuf: unchanged, as the version `3.11.4` is locked
1. Upgraded Java dependencies for `amazon-kinesis-producer/pom.xml`
* maven-compiler-plugin: 3.1 -> 3.7.0
* maven-javadoc-plugin: 2.10.3 -> 3.4.1
* maven-source-plugin: 3.0.1 -> 3.2.1
* aws-sdk-core: 1.11.960 -> 1.12.296
* guava: 29.0-jre -> 31.1-jre
* slf4j-api: 1.7.25 -> 2.0.0
* protobuf-java: 3.16.1 -> 3.21.5
* commons-io: 2.7 -> 2.11.0
* schema-registry-serde: 1.1.9 -> 1.1.13
* junit: 4.13.1 -> 4.13.2
* jakarta.xml.bind-api: 2.3.2 -> 4.0.0
* confluex-mock-http: (removed) 0.4.3
* …
=> Upgrade the dependencies used in bootstrap + Java dependencies

bootstrap.sh
- Due to https://github.com/openssl/openssl/issues/18720, openssl must be downgraded from 1.1.1q to 1.1.1n when compiling KPL on Mac.
- Built and tested on a Mac 
=> Update bootstrap.sh to work on three platforms

CMakeLists.txt, aws/kinesis/core/configuration.h, aws/kinesis/core/kinesis_producer.cc, aws/kinesis/core/kinesis_producer.h, aws/kinesis/core/pipeline.h, aws/kinesis/core/put_records_context.h, aws/kinesis/core/retrier.h, aws/kinesis/core/shard_map.cc, aws/kinesis/core/shard_map.h, aws/kinesis/core/test/retrier_test.cc, aws/kinesis/core/test/shard_map_test.cc, aws/kinesis/main.cc, aws/kinesis/protobuf/config.pb.cc, aws/kinesis/protobuf/config.pb.h, aws/kinesis/protobuf/config.proto, bootstrap.sh, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/HashedFileCopier.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/UserRecord.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/protobuf/Config.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/HashedFileCopierTest.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/KinesisProducerTest.java
1. In order for users to benefit from account endpoints, StreamARN is included into both ListShards and PutRecords requests
1. Updated few dependencies to the most recent versions: aws-sdk-cpp. curl, and openssl, zlib
1. Added the STS dependency for building the StreamARN
- Include STS endpoint and STS port in the configuration, and protobuf is updated accordingly
- When the STS call fails, the KPL would exit. Therefore we can assure that KPL is running with StreamARNs
1. Fixed issue 
- #445
- #452
*Testing*
- Compiled in OSX, and tested with `amazon-kinesis-producer-sample`
```
[kpl-daemon-0003] INFO com.amazonaws.services.kinesis.producer.LogInputStreamReader - [2022-12-19 10:55:35.409865] [0x0000fe11][0x0000700009aea000] [info] [AWS Log: …
```
=> Use sts to construct stream arn

aws/kinesis/main.cc, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/HashedFileCopier.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/HashedFileCopierTest.java
- Revert the upgrade of jakarta.xml.bind to be backward-compatible with Java8
- Add more logs to verify that IMDSV2 is used correctly for getting region info for KPL running in EC2 instances
*Test*
- Confirmed that both Java11 and Java8 can build successfully with recently introduced dependencies for javax
- IMDS validation
```
[kpl-daemon-0003] INFO com.amazonaws.services.kinesis.producer.LogInputStreamReader - [2023-01-03 16:44:13.525020] [0x00008a94][0x000000011715b600] [info] [main.cc:257] Region has been successfully set to us-east-1 from user's input configuration
[kpl-daemon-0003] INFO com.amazonaws.services.kinesis.producer.LogInputStreamReader - [2023-01-04 00:56:42.318065] [0x00003389][0x0000ffff9076f010] [info] [main.cc:269] …
```
=> Revert the upgrade of jakarta.xml.bind to be backward-compatible with Java8

bootstrap.sh
SDK is making IMDSv1 calls on GetCurrentRegion() in the version aws-sdk-cpp v1.10.32, this behavior has been recently been updated how that works in v1.10.56. 
Updating the version.
=> updating AWS SDK CPP version

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, aws/kinesis/core/shard_map.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
- https://github.com/awslabs/amazon-kinesis-producer/issues/481
- Remove the `StreamArn` parameter when ListShards fetches the next page using `NextToken`
* Testing*
Tested locally with the code snippet
```
void ShardMap::list_shards(const Aws::String& next_token) {
Aws::Kinesis::Model::ListShardsRequest req;
req.SetMaxResults(1);
if (!next_token.empty()) {
LOG(info) << "[DEBUG] Updating shard map for stream \"" << stream_ << "\", the max result has been set to 1";
req.SetNextToken(next_token);
} else {
...
}
```
and verified that the next page of shards can be successfully loaded:
```
[kpl-daemon-0003] INFO com.amazonaws.services.kinesis.producer.LogInputStreamReader - [2023-02-17 10:28:06.754721] [0x00007c48][0x0000700003987000] [info] …
```
=> Remove the stream arn parameter when the next token is present

CMakeLists.txt
Fix the build error after upgrading the aws sdk cpp version
```
Target "kinesis_producer" links to target "ZLIB::ZLIB" but the target was
not found.  Perhaps a find_package() call is missing for an IMPORTED
target, or an ALIAS target is missing?
```
=> Update the CMakeList

aws/kinesis/main.cc, aws/utils/logging.cc, aws/utils/logging.h, bootstrap.sh
1. Upgrade SDK version to avoid s2n_cleanup related memory leak
2. Fix resource cleanup on KPL end to avoid memory leak
=> Fix some memory leak cases in legacy code

aws/kinesis/core/kinesis_producer.cc, aws/kinesis/core/kinesis_producer.h, aws/kinesis/core/pipeline.h, aws/kinesis/core/user_record.cc, aws/kinesis/core/user_record.h, aws/kinesis/protobuf/messages.pb.cc, aws/kinesis/protobuf/messages.pb.h, aws/kinesis/protobuf/messages.proto, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/IKinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/UserRecord.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/protobuf/Config.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/protobuf/Messages.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/KinesisProducerTest.java
Issue #, if available:
N/A
Description of changes:
In order for users to benefit from CAA - cross account access, StreamARN parameter is included into the requests.
Testing:
Compiled and tested with amazon-kinesis-producer-sample
```
[kpl-daemon-0003] INFO com.amazonaws.services.kinesis.producer.LogInputStreamReader - [2023-12-13 17:59:01.756904] [0x00002bd9][0x00007fa212063700] [info] [kinesis_producer.cc:226] Created pipeline for stream "kpltest"
[kpl-daemon-0003] INFO com.amazonaws.services.kinesis.producer.LogInputStreamReader - [2023-12-13 17:59:01.774553] [0x00002bd9][0x00007fa212063700] [info] [pipeline.h:226] StreamARN "arn:aws:kinesis:us-west-2:056772968073:stream/kpltest" has been successfully configured, and will be used in requests including ListShards and PutRecords …
```
=> Add StreamARN parameter to support CAA

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
Preparing for KPL release 0.15.9
[[#552](https://github.com/awslabs/amazon-kinesis-producer/pull/552)] Add StreamARN parameter to support CAA
* StreamARN parameter can be now be used to benefit from Cross account access for KPL requests.
=> prepare for KPL release 0.15.9

java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/BinaryToHexConverter.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/HashedFileCopier.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/BinaryToHexConverterTest.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/HashedFileCopierTest.java
This is related to https://github.com/awslabs/amazon-kinesis-producer/issues/452 and would remove the need for https://github.com/awslabs/amazon-kinesis-producer/pull/522.
The jaxb depedency (`javax.xml.bind`) is used in a couple of classes to convert a binary array to a hex string. As suggested in https://github.com/awslabs/amazon-kinesis-producer/issues/452#issuecomment-1371445572 it is possible to drop the dependency and just have a simple converter instead. This will also remove the need to care about potential `jakarta` namespace switch in the future. This is important because currently trying to use the kinesis-producer library together with Spring 6 + latest Spring JPA/Hibernate results in errors. Removing the jaxb dependency from …
=> Drop dependency on jaxb for converting binary arrays to hex

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java
* Even though there is a thread model defined in settings, Daemon is always using POOLED which in high volume scenatios will produce Out of Memory errors and CPU problems.
=> [Fix] Thread Model is not being applied.

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/KinesisProducerTest.java
*Issue #, if available:* [489](https://github.com/awslabs/amazon-kinesis-producer/issues/489)
- Refactored `getOldestRecordTimeInMillis` to avoid a possible `NullPointerException` which can be caused by a race condition
- Added a simple unit test for this method
---
=> fix null pointer exception in getOldestRecordTimeMillis

aws/metrics/metrics_manager.cc
*Issue #, if available:* https://github.com/awslabs/amazon-kinesis-producer/issues/437
CloudWatch will throw the `MissingParameter: The parameter MetricData.member.x.Dimensions.member.y.Value is required.` error if a `Dimension.value` is an empty string or contains only whitespace.
So, to prevent the error, I added a simple check to make sure a value is not empty or all whitespace before we create a `Dimension` with it.
Unfortunately, I was not able to run the test suite for this project, so I regrettably have not included a unit test.
---
=> check if dimension value is blank before using it

aws/utils/signal_handler.cc
`sys_siglist` is deprecated and has already been removed from the GNU C library, causing this project not to build on some systems.
1. Replaced all usage of `sys_siglist` with `strsignal`
2. Refactor: pulled out duplicate code into a local variable
=> replace all usage of sys_siglist with strsignal

aws/kinesis/core/pipeline.h, aws/kinesis/core/test/shard_map_test.cc, aws/utils/logging.cc
N/a
Fix build after upgrading CPP SDK version.
The SDK upgrade caused two failures:
1. ListShardAsync argument order is changed from listShardAsync(req, handler, context) to listShardAsync(handler, context, req)
2. The interface `LogSystemInterface` has an addition of a none default interface method.
=> Fix build issue after cpp sdk upgrade

CMakeLists.txt, bootstrap.sh, java/amazon-kinesis-producer/pom.xml
Upgrade the following dependencies to address CVE violations
- curl 7.86.0 -> 8.12.0
- openssl 1.1.1s -> 3.4.0
- zlib 1.2.13 -> 1.3.1
- schema-registry-serde 1.1.22 -> 1.1.23
Updated third_party lib in `bootstrap` to point to correct folder for certain libraries as part of openssl upgrade. Fix `boost` url as that link is dead now. Tested by successfully running `bootstrap`
=> Upgrade curl, openssl, zlib, and schema-registry-serde

java/amazon-kinesis-producer/src/main/java/software/amazon/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/software/amazon/kinesis/producer/KinesisProducerConfiguration.java, java/amazon-kinesis-producer/src/test/java/software/amazon/kinesis/producer/KinesisProducerTest.java
We use 0.14.2 of the library. When we upgraded to any version beyond 0.14.2, we saw a significant drop in throughput of the records that we were able to send to KPL. 
We've narrowed this down to the oldestFutureTracker feature that was introduced in 0.14.3. We disabled the feature in 0.14.3 and then saw back to normal throughput. 
The current understanding is that the PriorityQueue starts off at a size of 10 items, but then grows which involves a lot of copying / moving etc. 
This PR introduces a flag to control enabling/disabling this oldest future tracking feature. 
Note how 0.14.2 and 0.14.3-wo-heap don't impact the time we spend in KPL.
=> Adding a feature flag (default enabled) to enable/disable oldest future tracking feature

aws/metrics/accumulator.h, aws/metrics/metrics_header.h, aws/metrics/metrics_manager.cc, aws/metrics/metrics_manager.h, aws/metrics/test/accumulator_test.cc
*Issue #, if available:* https://github.com/awslabs/amazon-kinesis-producer/issues/188
*Description of changes:* Fixes a race condition between the metrics manager and the metrics accumulator that could cause missed data points. If these were the only data points in the last 60 seconds, this could cause CloudWatch to fail the PutMetricData request as it would try to upload the default values in C++ Boost accumulators.
=> Fix metrics upload race condition

java/amazon-kinesis-producer/src/main/java/software/amazon/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/test/java/software/amazon/kinesis/producer/KinesisProducerTest.java
For some reason the library is also tracking oldest futures for metrics. This also adds the flag for disable future tracking for metrics requests. 
=> Also disabling oldest future tracking for Metrics

aws/kinesis/core/configuration.h, aws/kinesis/main.cc, java/amazon-kinesis-producer/src/main/java/software/amazon/kinesis/producer/KinesisProducerConfiguration.java
When enableCoredumps is false, set core file size limits to zero so no core dump is generated to make coredump generation controllable. When unset, default to environment default  
```
[kpl-daemon-0003] INFO software.amazon.kinesis.producer.LogInputStreamReader - [2025-07-25 08:19:53.040517] [0x00054aef][0x00007f4997059240] [info] [main.cc:334] Disabling core dumps: Current soft limit is 18446744073709551615; hard limit is 18446744073709551615; setting soft limit to 0
```
Updated code to abort() after core dump limit is set and tested three scenarios
1. unset - core dump file generated 
2. false - not generated 
3. true - generated 
Also, run the code without the abort() and code execute without issue
By submitting this pull request, I confirm that you can use, …
=> Allow coredumps to be disabled
