awslabs/amazon-kinesis-producer

java/amazon-kinesis-producer-sample/pom.xml
Updated the sample to use 1.7.0 of the Kinesis Client Library, and
0.12.0 of the Kinesis Producer Library.
=> Updated Sample to the Newest Versions

aws/kinesis/core/kinesis_producer.cc, aws/kinesis/main.cc, aws/utils/logging.cc, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java
Added region detection for BJS that overrides the endpoints for those regions.
=> Added Configuration Overrides for BJS

java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/SampleConsumer.java
Update the import for a moved class.
=> Updated for KCL 1.7.2

aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/LogInputStreamReader.java
Update version numbers to 0.12.4.
=> Prepare for Release 0.12.4

aws/utils/processing_statistics_logger.cc
=> Missing Underscore

README.md
Written up the release notes for the Amazon Kinesis Producer release 0.12.4.
=> Release Notes for Amazon Kinesis Producer 0.12.4

CMakeLists.txt, bootstrap.sh
This compiles the native version of the KPL to support macOS 10.9 and greater.
Fixes #117
=> Set the minimum macOS version to 10.9

aws/kinesis/core/kinesis_producer.cc
Updated the version number in preparation of upcoming release.
=> Updated version number for release.

README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
Updated version, and added release notes for the 0.12.7 release.
=> Release Notes for 0.12.7

java/amazon-kinesis-producer/pom.xml
=> Advance AWS SDK for Java to 1.11.245

README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer/pom.xml
Added release notes.
Updated POM version to 0.12.9
Updated user agent string to 0.12.9
Updated AWS Java SDK version.
=> Prepare for release 0.12.9 of the Amazon Kinesis Producer Library

README.md
Added additional pull request to release notes
=> Updated release notes with additional change

README.md, java/amazon-kinesis-producer/pom.xml
* Bumping minor version so we can add windows binary as well towards Apache 2.0 release
=> Including windows binary towards Apache 2.0 release

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java
N/A
Fix typo which referred to Partition Key as "Parition Key"
=> Fix error message typo

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
* Preparing for 0.14.0 release
Updated README, CHANGELOG, etc preparing for release 0.14.0
=> Initial PR for KPL Release 0.14.0 (#2)

CHANGELOG.md, README.md
Adding latest changes to current release target README description.
=> Adding more release notes for release 0.14.0

java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/MetricsAwareSampleProducer.java, java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/SampleConsumer.java, java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/SampleProducer.java, java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/SampleProducerConfig.java
Added more configurations to sample producer to run without modifying code
=> Added more configurations to sample producer to run without modifying code

README.md
Adding details for back-pressure to README and linking to the blog post for implementing Efficient and Reliable Producers which contains sample back-pressure logic.
=> Adding Backpressure callout to README

.travis.yml, README.md, bootstrap.sh
Mac OSX and Linux AL2012 build automations via Travis CI.
=> Linux and OSX Build Automation

.travis.yml, bootstrap.sh, java/amazon-kinesis-producer/pom.xml
=> Fix Travis CI build issues

CHANGELOG.md, README.md
Added Release notes for 0.14.1 in README.md and CHANGELOG.md
=> Adding release notes for release 0.14.1 in README.md and CHANGELOG.md

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java
=> Fixing bug to make the executor service to use 4*num_cores threads.

java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/IKinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/UserRecord.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstanceTest.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfigurationTest.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/KinesisProducerTest.java
Issue: https://github.com/awslabs/amazon-kinesis-producer/issues/314
*Issue #, if available:* https://github.com/awslabs/amazon-kinesis-producer/issues/314
This change adds support for Schema Registry in KPL.
=> Add support for Schema Registry.

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
*Description of changes:* Adding release notes for 0.14.2 release.
=> Adding release notes for 0.14.2 release.

aws/kinesis/core/kinesis_producer.cc, aws/metrics/metrics_manager.cc
*Description of changes:* Changing cw client retry strategy to use default SDK strategy.
=> Changing cw client retry strategy to use default SDK strategy.

java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/SampleProducer.java, java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/SampleProducerConfig.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/FutureTimedOutException.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/IKinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.java
=> Adding timeout on futures at Java layer.

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
*Description of changes:* Adding release notes for 0.14.3 release.
=> Adding release notes for 0.14.3 release.

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
*Description of changes:* Adding release notes for 0.14.4 release.
=> Adding release notes for 0.14.4 release.

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
*Description of changes:* Adding release notes for 0.14.5 release.
=> Adding release notes for 0.14.5 release.

java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
*Description of changes:* Updating Java SDK version in KPL.
Tested sanity locally by running the KPL with the latest SDK.
=> Updating Java SDK version in KPL.

.travis.yml
*Issue #, if available:* 
*Description of changes:* Updated travis build awscli. This was failing before with awscli build error
Build passed - https://travis-ci.com/github/awslabs/amazon-kinesis-producer/builds/219662892 
=> Updated travis build awscli.

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
*Description of changes:* Adding release notes for 0.14.6 release.
=> Adding release notes for 0.14.6 release.

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
=> Release 0.14.7

CHANGELOG.md, README.md
=> 0.14.7 Release

java/amazon-kinesis-producer/pom.xml
*Description of changes:* Bump up Glue Schema Registry to 1.1.1
=> Bump up Glue Schema Registry to 1.1.1

java/amazon-kinesis-producer-sample/README.md
Changed `Amazon Liunx` to `Amazon Linux`
=> Fix Amazon Linux typo in README.md

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml
=> Preparing for release 0.14.8

bootstrap.sh
=> Upgrading dependencies for build script

java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java-templates/KinesisProducerLibraryPackage.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
=> Using a hard-coded string for Glue user agent

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
=> Release 0.14.10

.travis.yml
=> FIxing travis build issues

java/amazon-kinesis-producer/pom.xml
Upgrading to use the latest version of GSR. 
Build successful.
=> Upgrading to latest version of GSR

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
=> Release 0.14.11

.travis.yml, bootstrap.sh
=> Fix travis build

bootstrap.sh
=> Fix aws-cpp branch.

.travis.yml, bootstrap.sh
=> Fix build issues in CI.

.travis.yml, bootstrap.sh
* Add wget to package download list.
* Use xcode9.3 for OSX build as the new one is not compatible with dependencies.
=> Fix build issues in CI. (#424)

java/amazon-kinesis-producer/pom.xml
=> Upgrade GSR version to 1.1.9

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
*Description of changes:* Release 0.14.12
=> Release 0.14.12

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
*Description of changes:* Release 0.14.13
=> Preparation for v0.14.13

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
Updated README, CHANGELOG, etc preparing for release 0.15.0
=> Prepare for KPL Release 0.15.0

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
- Prepare for KPL Release 0.15.1
=> Prepare for KPL Release 0.15.1

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
=> Upgrade Java dependencies

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
Preparing for KPL release 0.15.3
=> Prepare for KPL release 0.15.3

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
Preparing for KPL release 0.15.4
=> Prepare for KPL Release 0.15.4

bootstrap.sh
Updating the AWS sdk cpp version
=> Updating aws cpp sdk version

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
Preparing for KPL release 0.15.6
=> preparing for release 0.15.6

aws/kinesis/core/test/shard_map_test.cc, aws/metrics/test/metrics_manager_test.cc
Changes needed where we inherit SDK’s Client classes and overrides the virtual async methods.
=> Code refactor for async method

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
Preparing for KPL release 0.15.7
=> Preparing for release 0.15.7

java/amazon-kinesis-producer/pom.xml
Upgrade GSR version to v1.1.17
=> Upgrade to latest version of GSR

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
*Preparing for release 0.15.8*
*Description of changes: [#537](https://github.com/awslabs/amazon-kinesis-producer/pull/537) Update to latest version of Glue Schema Registry library*
=> Preparing for release 0.15.8

java/amazon-kinesis-producer/pom.xml
To fix build issue on CodeBuild
Adding direct lombok dependency in maven pom.xml
=> Fix build issue

aws/kinesis/core/kinesis_producer.cc, aws/kinesis/core/kinesis_producer.h, aws/kinesis/core/pipeline.h, aws/kinesis/core/user_record.cc, aws/kinesis/core/user_record.h, aws/kinesis/protobuf/messages.pb.cc, aws/kinesis/protobuf/messages.pb.h, aws/kinesis/protobuf/messages.proto, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/IKinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/UserRecord.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/protobuf/Config.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/protobuf/Messages.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/KinesisProducerTest.java
This reverts commit 7cf965645b62e44691879929d2974418b4b3d1e5.
=> Revert "Add streamARN parameter to support CAA"

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/IKinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/UserRecord.java
Support for CAA
Adding the implementation for addUserRecord 
=> Fixing bug for addUserRecord

CHANGELOG.md, README.md, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
* [#554](https://github.com/awslabs/amazon-kinesis-producer/pull/554) Fix bug for addUserRecord
=> prepare for KPL release 0.15.10

aws/kinesis/core/kinesis_producer.cc, aws/kinesis/core/kinesis_producer.h, aws/kinesis/core/pipeline.h, aws/kinesis/core/user_record.cc, aws/kinesis/core/user_record.h, aws/kinesis/protobuf/messages.pb.cc, aws/kinesis/protobuf/messages.pb.h, aws/kinesis/protobuf/messages.proto, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/IKinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/UserRecord.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/protobuf/Config.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/protobuf/Messages.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/KinesisProducerTest.java
Reverting the commits that were seen causing the issue. 
[Revert "Add StreamARN parameter to support CAA"](https://github.com/awslabs/amazon-kinesis-producer/commit/1caa98300347c2e93190f5d52e1440e7e7f3086a)
[Revert "Fixing bug for addUserRecord"](https://github.com/awslabs/amazon-kinesis-producer/commit/59e431d276bd62ad522c574c76356f11a4ecbbd3)
[Revert "Fixing bug for addUserRecord"](https://github.com/awslabs/amazon-kinesis-producer/commit/47d2c7d5a2a42cdf474815f139ce3bfcaf90ecdb)
=> Reverting CAA related changes 

CHANGELOG.md, README.md
=> Update wording in ReadMe release 0.15.10

java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java
Reverting the thread model change. 
=> Revert "[Fix] Thread Model is not being applied."

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
Prepare for release 0.15.11
Reference PR: https://github.com/awslabs/amazon-kinesis-producer/pull/390/files
=> Preparation for release 0.15.11

java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/Daemon.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/LogInputStreamReader.java, java/amazon-kinesis-producer/src/test/java/com/amazonaws/services/kinesis/producer/KinesisProducerTest.java
Migrate commons-lang to new maven package (org.apache.commons:commons-lang3).
=> upgrade to commons lang 3

bootstrap.sh, java/amazon-kinesis-producer/pom.xml
*Issue #, if available:* https://github.com/awslabs/amazon-kinesis-producer/issues/592
- Updated both the C++ and Java AWS SDK to the latest available version
---
=> update aws sdk to latest v1 version

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
Preparation for release 0.15.12
=> Preparation for release 0.15.12

aws/kinesis/core/kinesis_producer.cc, aws/kinesis/main.cc, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.java
*Description of changes:* Making caFile option configurable in KPL configuration 
=> make caFile option configurable

aws/kinesis/core/kinesis_producer.h, aws/kinesis/test_driver.cc
*Issue #, if available:* 
*Description of changes:* include caFile in test_driver and kinesis_producer.h
=> include caFile in test_driver and kinesis_producer.h

aws/kinesis/core/kinesis_producer.cc, bootstrap.sh, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer-sample/src/com/amazonaws/services/kinesis/producer/sample/SampleProducerConfig.java, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
=> Prepare for v0.15.13 release

CHANGELOG.md
Add changelog for release v1.0.0
=> Add release notes for v1.0.0

README.md
Update README with changelog and change some wordings. Also remove Travis build status as it is not working
=> Update README with 1.0.0 changelog and other minor updates

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/software/amazon/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
=> Prepare for KPL release 1.0.1

java/amazon-kinesis-producer/src/main/java/software/amazon/kinesis/producer/KinesisProducer.java, java/amazon-kinesis-producer/src/main/java/software/amazon/kinesis/producer/KinesisProducerConfiguration.java, java/amazon-kinesis-producer/src/test/java/software/amazon/kinesis/producer/KinesisProducerTest.java
Reverts awslabs/amazon-kinesis-producer#637
=> Revert "Adding a feature flag (default enabled) to enable/disable oldest future tracking feature"

java/amazon-kinesis-producer/src/test/java/software/amazon/kinesis/producer/KinesisProducerTest.java
=> Align producer tests with new metrics upload scheduling

bootstrap.sh
=> Add without-libpsl flag to MacOS libcurl build

CHANGELOG.md, README.md, aws/kinesis/core/kinesis_producer.cc, java/amazon-kinesis-producer-sample/pom.xml, java/amazon-kinesis-producer/pom.xml, java/amazon-kinesis-producer/src/main/java/software/amazon/kinesis/producer/GlueSchemaRegistrySerializerInstance.java
=> Prepare for KPL release v1.0.3
